Feature/portfolio mobile structure
RichardChileya/MobileSkeleton pull request #2
Opened 2022-07-01 16:43 UTC by RichardChileya

#his is my second Microverse project and this is my first branch.
#Things added include: 
  The headline section of my portfolio project. About me in HTML 
  Style work section for styling the portfolio page.
  Debugging of HTML and CSS

2022-07-01 22:04 UTC, tresorsawasawa requested changes
# STATUS: REQUEST CHANGES :recycle::recycle: 

Hi @RichardChileya 
Great work on making the changes requested by the previous reviewer  👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

## NOTICE
Make sure you implemented all the required changes before requesting a new **code review request. I know you can do that :muscle: :muscle: **

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-01 22:04 UTC, tresorsawasawa commented on styles.css
> +}
- [ **OPTIONAL** ] I think it would be better if you assign to your classes some **meaningful names** to make your code more readable.

2022-07-01 22:07 UTC, tresorsawasawa commented
## NOTICE
Hi @RichardChileya 
**Make sure you implemented all the required changes before requesting a new **code review request. I know you can do that :muscle: :muscle:**

2022-07-02 16:19 UTC, BertrandConxy requested changes
Hi @RichardChileya , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.


 ## Highlights 💪 
- no linter errors
- descriptive PR
- good commit message
- your codes are clean


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me  @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-02 16:19 UTC, BertrandConxy commented on index.html
> +                        <li><a href="#"><img src="./images/fingers.png" alt="fingers-icon"></a><li>
- [ ] I really appreciate your effort in trying to implement what the previous reviewer stated 👏. However, I am very sorry to tell you that these images are still broken. try to look at the current design you have here 👇 
![image](https://user-images.githubusercontent.com/90222110/177007953-26892896-2660-4e30-bad4-83b646803429.png)

I have noticed that it is due to that the extensions you added to the images here are not the same as the ones you have in your `images` folder. Please look at this screenshot 👇 
![image](https://user-images.githubusercontent.com/90222110/177008176-f66e98a7-bb1c-45b8-99b6-f5727903c32f.png)
For example; on the GitHub image. You used the `png` extension, while in your `images folder`, you have `jpg`
I hope you understand what I mean 😃 💡 . so please try to use the right extension here in your HTML matching the ones you have for your images in the `images` folder

2022-07-02 16:52 UTC, algerina requested changes
Hi @RichardChileya ,

Good job so far!
You did a great job however, there are some issues that you still need to work on to go to the next project but you are almost there!


Highlights
May I highlight the following:

The repo looks professional.heavy_check_mark
There are no linter errorsheavy_check_mark
You have descriptive PRheavy_check_mark
Your project looks goodheavy_check_mark
Required Changes recycle
Check the comments under the review.

Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!clapclapclap

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the Code reviews limits policy you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this form.

2022-07-02 16:52 UTC, algerina commented on index.html
> +                        <li><a href="#"><img src="./images/fingers.png" alt="fingers-icon"></a><li>
- [ ] The links to your social media icons are broken, please fix the issue by puting the right name of the image file.
Example:
for Twitter icon replace ` <li><a href="#"><img src="./images/twitter.png" alt="twitter-icon"></a></li>
`
with `  <li><a href="#"><img src="./images/twitter.jpg" alt="twitter-icon"></a></li>
`

2022-07-02 20:22 UTC, vickymarz approved these changes
Hi @RichardChileya, 

# 🟢  Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 
<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-02 20:49 UTC, merged